/* 
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS lists;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users_lists;
DROP TABLE IF EXISTS todos;

 
CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	is_admin BOOLEAN NOT NULL DEFAULT 0 CHECK (is_admin IN (0, 1)) 
); 

CREATE TABLE IF NOT EXISTS lists (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	role_name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users_lists (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	fk_users_id INTEGER NOT NULL,
	fk_lists_id INTEGER NOT NULL,
	fk_roles_id INTEGER NOT NULL,
	
	FOREIGN KEY(fk_users_id) REFERENCES users(id),
	FOREIGN KEY(fk_lists_id) REFERENCES lists(id),
	FOREIGN KEY(fk_roles_id) REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS todos (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	todo TEXT NOT NULL,
	done BOOLEAN NOT NULL DEFAULT 0 CHECK (done IN (0, 1)),
	fk_lists_id INTEGER NOT NULL,
	FOREIGN KEY(fk_lists_id) REFERENCES lists(id)
);

INSERT INTO roles (role_name) VALUES ('owner'), ('guest') ON CONFLICT DO NOTHING;


SELECT * FROM users;
SELECT * FROM lists;
SELECT * FROM roles;
SELECT * FROM users_lists;
SELECT * FROM todos;
*/